name: WorldMagic
description: "Progressive world manager"
version: '$version'
authors: [hotwop]

main: io.hotwop.worldmagic.WorldMagic
bootstrapper: io.hotwop.worldmagic.WorldMagicBootstrap

api-version: '1.20.6'

permissions:
  worldmagic.command:
    description: WorldMagic command permission